package jim.src;

public enum TokenType {
    LEFT_PAREN, RIGHT_PAREN, PLUS, MINUS, STAR, SLASH, MOD, CARROT, DOUBLE, COMMA, EQUAL, LET, SEMICOLON,
    IDENTIFIER, FUNCTION, RETURN, LEFT_BRACE, RIGHT_BRACE, LEFT_SQUARE, RIGHT_SQUARE, EOF
}
